### ISSUE TITLE
Geographical verification

### ISSUE THREAD

**Issue by Sanithovski** [csci104/queueing#15]
Students report that some people are abusing the system when they’re not physically present at SAL. They are asking for a verification procedure.

One of my simple ideas: a short pin that can be refreshed by staff. The staff can view the code and display it at SAL. Students need the code to submit their ticket.

**Comment by noahbkim** [comment]
I like this idea and solution, however I worry that students will tell their friends what the code is, thereby disadvantaging students who don't have friends in OH. Any thoughts?

**Comment by Sanithovski** [comment]
I don't think this matters any more this semester... maybe reopen it in the future.
